version: "3.9"
services:
  app:
   build: .
   ports:
     - "8091:8000"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - db:/var/lib/postgresql/data

  nextjs:
    build:
      dockerfile: Dockerfile-nextjs
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - app
volumes:
    db: