version: "3.9"
services:
  app:
   build: .
   ports:
     - "8090:8000"
  
  nextjs:
    build:
      dockerfile: Dockerfile-nextjs
    ports:
      - "3000:3000"
    volumes:
      - ./nextjs:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - app
volumes:
    db: