version: "3.9"
services:
  app:
   build: .
   ports:
     - "8091:8000"
   volumes:
     - db.sqlite3:/app/db.sqlite3
  nextjs:
    build:
      dockerfile: Dockerfile-nextjs
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - app
volumes:
    db: