FROM node:18-alpine

# Set work directory
WORKDIR /app

# Copy package files
COPY frontendapp/package*.json ./

# Install dependencies
RUN npm install --legacy-peer-deps

# Copy application files
COPY frontendapp/ .

# Build application
RUN npm run build

# Expose port
EXPOSE 3000


# Start the application
CMD ["npm", "run", "start"]